version: "3"
services:
  redis:
    image: redis
    ports:
     - "6379:6379"
  go-app:
    build: .
    environment:
      - CACOO_REDIS_HOST=redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - redis
  